spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME} # MySQL JDBC 드라이버 클래스 이름
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql # 사용할 DB 유형 지정 (MySQL)
    database-platform: ${JPA_DATABASE_PLATFORM} # Hibernate에서 사용할 MySQL 방언(dialect) 지정
    show-sql: true # 실행된 SQL 쿼리를 콘솔에 출력할지 여부
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO} # 애플리케이션 실행 시 DB 스키마의 상태 설정
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL} # 출력되는 SQL 쿼리를 보기 좋게 포맷팅

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  jwt:
    secret: ${JWT_SECRET}
    token:
      access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
      refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}